//! In-memory model of a `SoundFont` 2 file.
//!
//! The model is structured (presets own zones, zones own generators and
//! modulators) rather than flat like the on-disk `pdta` record arrays; the
//! flat bag/generator/modulator indices are resolved by [`crate::parse`] and
//! regenerated by [`crate::write`]. Instruments and samples are referenced by
//! index into [`SoundFont::instruments`] / [`SoundFont::samples`] from
//! generator amounts, exactly as on disk.

use std::fmt;

/// Length of the fixed name field in preset, instrument, and sample records.
pub const NAME_LEN: usize = 20;

/// Generator operator that links a preset zone to an instrument (spec: `instrument`, 41).
pub const GEN_INSTRUMENT: u16 = 41;
/// Generator operator that links an instrument zone to a sample (spec: `sampleID`, 53).
pub const GEN_SAMPLE_ID: u16 = 53;
/// Generator operator restricting a zone to a MIDI key range (spec: `keyRange`, 43).
pub const GEN_KEY_RANGE: u16 = 43;
/// Generator operator restricting a zone to a velocity range (spec: `velRange`, 44).
pub const GEN_VEL_RANGE: u16 = 44;

/// `sfSampleType` flag marking a sample stored in ROM.
pub const SAMPLE_TYPE_ROM: u16 = 0x8000;
/// `sfSampleType` bits that indicate the sample participates in a linked
/// (stereo or chained) pair: `rightSample` (2), `leftSample` (4), `linkedSample` (8).
pub const SAMPLE_TYPE_LINKED_MASK: u16 = 2 | 4 | 8;
/// `sfSampleType` flag marking an Ogg-Vorbis-compressed sample.
///
/// This is the SF3 convention established by `MuseScore`: `dwStart`/`dwEnd`
/// are then byte offsets of the compressed stream, and loop points are
/// relative to the decoded sample.
pub const SAMPLE_TYPE_COMPRESSED: u16 = 0x10;

/// On-disk record sizes in bytes, used by the parser and writer.
pub(crate) mod record {
    pub const PHDR: usize = 38;
    pub const BAG: usize = 4;
    pub const MOD: usize = 10;
    pub const GEN: usize = 4;
    pub const INST: usize = 22;
    pub const SHDR: usize = 46;
}

/// Decodes NUL-terminated text from an SF2 record or `INFO` chunk: the bytes
/// up to the first NUL, as UTF-8 when valid and otherwise as Latin-1 (the
/// spec says ASCII, but real-world fonts often store Latin-1 such as `0xA9`
/// for `©`). Every byte maps to a character, so nothing is ever lost.
#[must_use]
pub fn decode_text(data: &[u8]) -> String {
    let end = data.iter().position(|&b| b == 0).unwrap_or(data.len());
    let text = &data[..end];
    std::str::from_utf8(text).map_or_else(
        |_| text.iter().map(|&b| char::from(b)).collect(),
        str::to_string,
    )
}

/// A fixed-size, NUL-padded name exactly as stored in SF2 records.
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub struct FixedName(pub [u8; NAME_LEN]);

impl FixedName {
    /// Builds a name from text, truncated to 19 bytes and NUL-padded.
    #[must_use]
    pub fn from_text(text: &str) -> Self {
        let mut bytes = [0u8; NAME_LEN];
        for (slot, byte) in bytes.iter_mut().take(NAME_LEN - 1).zip(text.bytes()) {
            *slot = byte;
        }
        Self(bytes)
    }

    /// Renders the name for display (see [`decode_text`]).
    #[must_use]
    pub fn to_display(&self) -> String {
        decode_text(&self.0)
    }
}

impl serde::Serialize for FixedName {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(&self.to_display())
    }
}

impl fmt::Display for FixedName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.to_display())
    }
}

impl fmt::Debug for FixedName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "FixedName({:?})", self.to_display())
    }
}

/// A generator: an operator and its raw 16-bit amount.
///
/// The amount is kept as the raw little-endian `u16`; whether it means a
/// signed value, an unsigned value, or a byte range depends on the operator.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Generator {
    /// Generator operator (`SFGenerator` in the spec).
    pub oper: u16,
    /// Raw generator amount.
    pub amount: u16,
}

/// A generator amount decoded according to the spec type of its operator.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize)]
#[serde(untagged)]
#[non_exhaustive]
pub enum GeneratorValue {
    /// `rangesType`: an inclusive low/high pair (`keyRange`, `velRange`).
    Range {
        /// Low end of the range.
        lo: u8,
        /// High end of the range.
        hi: u8,
    },
    /// `wAmount`: an unsigned index (`instrument`, `sampleID`).
    Unsigned(u16),
    /// `shAmount`: a signed value (every other operator).
    Signed(i16),
}

impl Generator {
    /// The amount decoded per the spec type of this generator's operator.
    #[must_use]
    pub const fn value(&self) -> GeneratorValue {
        let [lo, hi] = self.amount.to_le_bytes();
        match self.oper {
            GEN_KEY_RANGE | GEN_VEL_RANGE => GeneratorValue::Range { lo, hi },
            GEN_INSTRUMENT | GEN_SAMPLE_ID => GeneratorValue::Unsigned(self.amount),
            _ => GeneratorValue::Signed(i16::from_le_bytes([lo, hi])),
        }
    }
}

impl serde::Serialize for Generator {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut row = serializer.serialize_struct("Generator", 4)?;
        row.serialize_field("oper", &self.oper)?;
        row.serialize_field("name", &generator_name(self.oper))?;
        row.serialize_field("amount", &self.amount)?;
        row.serialize_field("value", &self.value())?;
        row.end()
    }
}

/// The spec name of a generator operator, when it is a defined one.
#[must_use]
pub const fn generator_name(oper: u16) -> Option<&'static str> {
    Some(match oper {
        0 => "startAddrsOffset",
        1 => "endAddrsOffset",
        2 => "startloopAddrsOffset",
        3 => "endloopAddrsOffset",
        4 => "startAddrsCoarseOffset",
        5 => "modLfoToPitch",
        6 => "vibLfoToPitch",
        7 => "modEnvToPitch",
        8 => "initialFilterFc",
        9 => "initialFilterQ",
        10 => "modLfoToFilterFc",
        11 => "modEnvToFilterFc",
        12 => "endAddrsCoarseOffset",
        13 => "modLfoToVolume",
        15 => "chorusEffectsSend",
        16 => "reverbEffectsSend",
        17 => "pan",
        21 => "delayModLFO",
        22 => "freqModLFO",
        23 => "delayVibLFO",
        24 => "freqVibLFO",
        25 => "delayModEnv",
        26 => "attackModEnv",
        27 => "holdModEnv",
        28 => "decayModEnv",
        29 => "sustainModEnv",
        30 => "releaseModEnv",
        31 => "keynumToModEnvHold",
        32 => "keynumToModEnvDecay",
        33 => "delayVolEnv",
        34 => "attackVolEnv",
        35 => "holdVolEnv",
        36 => "decayVolEnv",
        37 => "sustainVolEnv",
        38 => "releaseVolEnv",
        39 => "keynumToVolEnvHold",
        40 => "keynumToVolEnvDecay",
        41 => "instrument",
        43 => "keyRange",
        44 => "velRange",
        45 => "startloopAddrsCoarseOffset",
        46 => "keynum",
        47 => "velocity",
        48 => "initialAttenuation",
        50 => "endloopAddrsCoarseOffset",
        51 => "coarseTune",
        52 => "fineTune",
        53 => "sampleID",
        54 => "sampleModes",
        56 => "scaleTuning",
        57 => "exclusiveClass",
        58 => "overridingRootKey",
        _ => return None,
    })
}

/// A modulator record (`sfModList`/`sfInstModList`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize)]
pub struct Modulator {
    /// Source modulator controller (`sfModSrcOper`).
    pub src_oper: u16,
    /// Destination generator (`sfModDestOper`).
    pub dest_oper: u16,
    /// Degree of modulation (`modAmount`).
    pub amount: i16,
    /// Secondary source controller (`sfModAmtSrcOper`).
    pub amount_src_oper: u16,
    /// Transform applied to the source (`sfModTransOper`).
    pub trans_oper: u16,
}

/// A preset or instrument zone: a modulator list and a generator list.
#[derive(Debug, Clone, PartialEq, Eq, Default, serde::Serialize)]
pub struct Zone {
    /// Generators, in on-disk order.
    pub gens: Vec<Generator>,
    /// Modulators, in on-disk order.
    pub mods: Vec<Modulator>,
}

impl Zone {
    /// The instrument this preset zone points to, if any.
    ///
    /// Per spec the `instrument` generator is the last one in the list; the
    /// last occurrence wins if a malformed file carries several.
    #[must_use]
    pub fn instrument_ref(&self) -> Option<u16> {
        last_amount(&self.gens, GEN_INSTRUMENT)
    }

    /// The sample this instrument zone points to, if any.
    #[must_use]
    pub fn sample_ref(&self) -> Option<u16> {
        last_amount(&self.gens, GEN_SAMPLE_ID)
    }
}

fn last_amount(gens: &[Generator], oper: u16) -> Option<u16> {
    gens.iter().rev().find(|g| g.oper == oper).map(|g| g.amount)
}

/// A preset (`phdr` record plus its resolved zones).
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize)]
pub struct Preset {
    /// Preset name.
    pub name: FixedName,
    /// MIDI program number (`wPreset`).
    pub program: u16,
    /// MIDI bank number (`wBank`); 128 is the GM percussion bank.
    pub bank: u16,
    /// Reserved field preserved verbatim (`dwLibrary`).
    pub library: u32,
    /// Reserved field preserved verbatim (`dwGenre`).
    pub genre: u32,
    /// Reserved field preserved verbatim (`dwMorphology`).
    pub morphology: u32,
    /// Zones, in on-disk order; a leading global zone has no instrument generator.
    pub zones: Vec<Zone>,
}

/// An instrument (`inst` record plus its resolved zones).
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize)]
pub struct Instrument {
    /// Instrument name.
    pub name: FixedName,
    /// Zones, in on-disk order; a leading global zone has no sample generator.
    pub zones: Vec<Zone>,
}

/// A sample header (`shdr` record).
///
/// For plain samples the offsets are in sample points (16-bit words) into the
/// `smpl` chunk. For SF3-compressed samples ([`Self::is_compressed`]) `start`
/// and `end` are BYTE offsets of the Ogg-Vorbis stream and the loop points
/// are relative to the decoded audio.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize)]
pub struct SampleHeader {
    /// Sample name.
    pub name: FixedName,
    /// First sample point (`dwStart`).
    pub start: u32,
    /// One past the last sample point (`dwEnd`).
    pub end: u32,
    /// Loop start point (`dwStartloop`).
    pub start_loop: u32,
    /// Loop end point (`dwEndloop`).
    pub end_loop: u32,
    /// Sample rate in Hz (`dwSampleRate`).
    pub sample_rate: u32,
    /// Original MIDI key number (`byOriginalPitch`).
    pub original_pitch: u8,
    /// Pitch correction in cents (`chPitchCorrection`).
    pub pitch_correction: i8,
    /// Index of the linked sample when this one is part of a pair (`wSampleLink`).
    pub sample_link: u16,
    /// Sample type flags (`sfSampleType`).
    pub sample_type: u16,
}

impl SampleHeader {
    /// Whether the sample lives in ROM (no data in the `smpl` chunk).
    #[must_use]
    pub const fn is_rom(&self) -> bool {
        self.sample_type & SAMPLE_TYPE_ROM != 0
    }

    /// Whether the sample is one half of a linked (stereo/chained) pair.
    #[must_use]
    pub const fn is_linked(&self) -> bool {
        self.sample_type & SAMPLE_TYPE_LINKED_MASK != 0
    }

    /// Whether the sample data is an SF3 Ogg-Vorbis stream.
    #[must_use]
    pub const fn is_compressed(&self) -> bool {
        self.sample_type & SAMPLE_TYPE_COMPRESSED != 0
    }

    /// Length of the sample in sample points.
    #[must_use]
    pub const fn len_points(&self) -> u32 {
        self.end.saturating_sub(self.start)
    }

    /// Bytes this sample occupies in the `smpl` chunk: SF3-compressed
    /// streams store `end - start` bytes, PCM stores two bytes per point.
    #[must_use]
    pub fn stored_bytes(&self) -> u64 {
        let len = u64::from(self.len_points());
        if self.is_compressed() { len } else { len * 2 }
    }
}

/// A raw `INFO` sub-chunk, preserved verbatim and in order.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InfoChunk {
    /// Four-character chunk id (e.g. `ifil`, `INAM`).
    pub id: [u8; 4],
    /// Raw chunk payload.
    pub data: Vec<u8>,
}

impl InfoChunk {
    /// The payload as text, when it is text: decoded per [`decode_text`] and
    /// free of control characters other than line breaks and tabs. Binary
    /// payloads such as the 4-byte `ifil` version yield `None`.
    #[must_use]
    pub fn text(&self) -> Option<String> {
        let text = decode_text(&self.data);
        let printable = !text.trim().is_empty()
            && text
                .chars()
                .all(|c| !c.is_control() || matches!(c, '\n' | '\r' | '\t'));
        printable.then_some(text)
    }
}

/// Serialised as `{id, text, bytes}`.
impl serde::Serialize for InfoChunk {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut row = serializer.serialize_struct("InfoChunk", 3)?;
        row.serialize_field("id", &String::from_utf8_lossy(&self.id))?;
        row.serialize_field("text", &self.text())?;
        row.serialize_field("bytes", &self.data.len())?;
        row.end()
    }
}

/// A complete in-memory `SoundFont`.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct SoundFont {
    /// `INFO` sub-chunks, order preserved.
    pub info: Vec<InfoChunk>,
    /// Raw 16-bit little-endian sample data (`smpl` chunk).
    pub sample_data: Vec<u8>,
    /// Optional least-significant bytes for 24-bit samples (`sm24` chunk).
    pub sample_data_24: Option<Vec<u8>>,
    /// Presets, in on-disk order (terminal record excluded).
    pub presets: Vec<Preset>,
    /// Instruments, in on-disk order (terminal record excluded).
    pub instruments: Vec<Instrument>,
    /// Sample headers, in on-disk order (terminal record excluded).
    pub samples: Vec<SampleHeader>,
}

impl SoundFont {
    /// Number of 16-bit sample points in the `smpl` chunk.
    #[must_use]
    pub const fn sample_points(&self) -> usize {
        self.sample_data.len() / 2
    }

    /// Payload of the first `INFO` sub-chunk with the given id, if present.
    #[must_use]
    pub fn info_chunk(&self, id: [u8; 4]) -> Option<&[u8]> {
        self.info
            .iter()
            .find(|c| c.id == id)
            .map(|c| c.data.as_slice())
    }

    /// `SoundFont` format version from the `ifil` chunk, as (major, minor).
    #[must_use]
    pub fn version(&self) -> Option<(u16, u16)> {
        let data = self.info_chunk(*b"ifil")?;
        if data.len() < 4 {
            return None;
        }
        Some((
            u16::from_le_bytes([data[0], data[1]]),
            u16::from_le_bytes([data[2], data[3]]),
        ))
    }

    /// The index of `index`'s partner when the two samples link to each
    /// other mutually — the only linkage this crate trusts. One-directional
    /// links (common in real-world fonts, e.g. Fluid R3 types samples as
    /// left/right but leaves every `wSampleLink` at 0) are treated as broken.
    #[must_use]
    pub fn mutual_link(&self, index: usize) -> Option<usize> {
        let sample = self.samples.get(index)?;
        if !sample.is_linked() {
            return None;
        }
        let partner_index = usize::from(sample.sample_link);
        if partner_index == index {
            return None;
        }
        let partner = self.samples.get(partner_index)?;
        (partner.is_linked() && usize::from(partner.sample_link) == index).then_some(partner_index)
    }

    /// Whether the 24-bit extension can be used, per SF2.04 §6.3: requires a
    /// non-empty `smpl` chunk, format version 2.04 or later, and an `sm24`
    /// length of exactly one byte per sample point, rounded up to even.
    /// Unusable `sm24` data is preserved by the writer but ignored by
    /// extraction (and flagged by validation).
    #[must_use]
    pub fn sm24_usable(&self) -> bool {
        let Some(data_24) = &self.sample_data_24 else {
            return false;
        };
        if self.sample_data.is_empty() || self.version() < Some((2, 4)) {
            return false;
        }
        let points = self.sample_points();
        data_24.len() == points + (points & 1)
    }

    /// Bank name from the `INAM` chunk, if present.
    #[must_use]
    pub fn name(&self) -> Option<String> {
        self.info_chunk(*b"INAM").map(decode_text)
    }
}

/// The structural dump format (`sf2-cutter dump`): name, version, `INFO`
/// chunks, presets, instruments, and sample headers. Sample audio is
/// summarised as byte counts rather than serialised.
impl serde::Serialize for SoundFont {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut font = serializer.serialize_struct("SoundFont", 8)?;
        font.serialize_field("name", &self.name())?;
        font.serialize_field("version", &self.version())?;
        font.serialize_field("info", &self.info)?;
        font.serialize_field("sample_data_bytes", &self.sample_data.len())?;
        font.serialize_field("sm24_bytes", &self.sample_data_24.as_ref().map(Vec::len))?;
        font.serialize_field("presets", &self.presets)?;
        font.serialize_field("instruments", &self.instruments)?;
        font.serialize_field("samples", &self.samples)?;
        font.end()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fixed_name_should_truncate_text_when_longer_than_nineteen_bytes() {
        // given
        let text = "a very long instrument name indeed";

        // when
        let name = FixedName::from_text(text);

        // then
        assert_eq!(name.to_display(), "a very long instrum");
        assert_eq!(name.0[NAME_LEN - 1], 0);
    }

    #[test]
    fn fixed_name_should_round_trip_when_text_is_short() {
        // given
        let text = "Piano";

        // when
        let name = FixedName::from_text(text);

        // then
        assert_eq!(name.to_display(), "Piano");
    }

    #[test]
    fn fixed_name_should_stop_at_first_nul_when_garbage_follows() {
        // given
        let mut bytes = [b'x'; NAME_LEN];
        bytes[0] = b'A';
        bytes[1] = 0;

        // when
        let name = FixedName(bytes);

        // then
        assert_eq!(name.to_display(), "A");
    }

    #[test]
    fn zone_should_report_instrument_ref_when_instrument_generator_present() {
        // given
        let zone = Zone {
            gens: vec![
                Generator {
                    oper: 8,
                    amount: 1000,
                },
                Generator {
                    oper: GEN_INSTRUMENT,
                    amount: 7,
                },
            ],
            mods: vec![],
        };

        // when
        let inst = zone.instrument_ref();

        // then
        assert_eq!(inst, Some(7));
    }

    #[test]
    fn zone_should_report_no_instrument_ref_when_zone_is_global() {
        // given
        let zone = Zone {
            gens: vec![Generator {
                oper: 8,
                amount: 1000,
            }],
            mods: vec![],
        };

        // when
        let inst = zone.instrument_ref();

        // then
        assert_eq!(inst, None);
    }

    #[test]
    fn sample_header_should_report_rom_when_rom_flag_set() {
        // given
        let header = sample_header_with_type(SAMPLE_TYPE_ROM | 1);

        // when / then
        assert!(header.is_rom());
        assert!(!sample_header_with_type(1).is_rom());
    }

    #[test]
    fn sample_header_should_report_compressed_when_sf3_flag_set() {
        // given / when / then
        assert!(sample_header_with_type(SAMPLE_TYPE_COMPRESSED | 1).is_compressed());
        assert!(!sample_header_with_type(1).is_compressed());
    }

    #[test]
    fn sample_header_should_report_stored_bytes_when_compressed_or_plain() {
        // given
        let mut header = sample_header_with_type(1); // 100 points -> 200 bytes

        // when / then
        assert_eq!(header.stored_bytes(), 200);
        header.sample_type = SAMPLE_TYPE_COMPRESSED | 1; // 100 BYTES of Ogg
        assert_eq!(header.stored_bytes(), 100);
    }

    #[test]
    fn sample_header_should_report_linked_when_left_or_right_flag_set() {
        // given / when / then
        assert!(sample_header_with_type(2).is_linked());
        assert!(sample_header_with_type(4).is_linked());
        assert!(sample_header_with_type(8).is_linked());
        assert!(!sample_header_with_type(1).is_linked());
    }

    #[test]
    fn generator_name_should_match_spec_table_when_checking_every_operator() {
        // given: SF2.04 section 8.1.2, operators 0..=58; None = unused/reserved
        let spec: [Option<&str>; 61] = [
            Some("startAddrsOffset"),
            Some("endAddrsOffset"),
            Some("startloopAddrsOffset"),
            Some("endloopAddrsOffset"),
            Some("startAddrsCoarseOffset"),
            Some("modLfoToPitch"),
            Some("vibLfoToPitch"),
            Some("modEnvToPitch"),
            Some("initialFilterFc"),
            Some("initialFilterQ"),
            Some("modLfoToFilterFc"),
            Some("modEnvToFilterFc"),
            Some("endAddrsCoarseOffset"),
            Some("modLfoToVolume"),
            None, // unused1
            Some("chorusEffectsSend"),
            Some("reverbEffectsSend"),
            Some("pan"),
            None, // unused2
            None, // unused3
            None, // unused4
            Some("delayModLFO"),
            Some("freqModLFO"),
            Some("delayVibLFO"),
            Some("freqVibLFO"),
            Some("delayModEnv"),
            Some("attackModEnv"),
            Some("holdModEnv"),
            Some("decayModEnv"),
            Some("sustainModEnv"),
            Some("releaseModEnv"),
            Some("keynumToModEnvHold"),
            Some("keynumToModEnvDecay"),
            Some("delayVolEnv"),
            Some("attackVolEnv"),
            Some("holdVolEnv"),
            Some("decayVolEnv"),
            Some("sustainVolEnv"),
            Some("releaseVolEnv"),
            Some("keynumToVolEnvHold"),
            Some("keynumToVolEnvDecay"),
            Some("instrument"),
            None, // reserved1
            Some("keyRange"),
            Some("velRange"),
            Some("startloopAddrsCoarseOffset"),
            Some("keynum"),
            Some("velocity"),
            Some("initialAttenuation"),
            None, // reserved2
            Some("endloopAddrsCoarseOffset"),
            Some("coarseTune"),
            Some("fineTune"),
            Some("sampleID"),
            Some("sampleModes"),
            None, // reserved3
            Some("scaleTuning"),
            Some("exclusiveClass"),
            Some("overridingRootKey"),
            None, // unused5
            None, // endOper
        ];

        // when / then
        for (oper, expected) in (0u16..).zip(spec) {
            assert_eq!(generator_name(oper), expected, "operator {oper}");
        }
        assert_eq!(generator_name(u16::MAX), None);
    }

    #[test]
    fn decode_text_should_fall_back_to_latin1_when_bytes_are_not_utf8() {
        // given / when / then
        assert_eq!(decode_text(b"Caf\xe9 \xa9 2008\0junk"), "Café © 2008");
        assert_eq!(decode_text("Flöte".as_bytes()), "Flöte");
        assert_eq!(decode_text(b"plain"), "plain");
    }

    #[test]
    fn info_text_should_return_text_when_payload_is_printable() {
        // given
        let chunk = |data: &[u8]| InfoChunk {
            id: *b"ICMT",
            data: data.to_vec(),
        };

        // when / then
        assert_eq!(chunk(b"hello\0").text().as_deref(), Some("hello"));
        assert_eq!(
            chunk(b"line1\nline2\t!\0").text().as_deref(),
            Some("line1\nline2\t!")
        );
        assert_eq!(
            chunk(b"\xa9 Someone\0").text().as_deref(),
            Some("© Someone")
        );
        assert_eq!(chunk(b"first\0second").text().as_deref(), Some("first"));
    }

    #[test]
    fn info_text_should_return_none_when_payload_is_binary_or_blank() {
        // given
        let chunk = |data: &[u8]| InfoChunk {
            id: *b"ifil",
            data: data.to_vec(),
        };

        // when / then
        assert_eq!(chunk(&[2, 0, 4, 0]).text(), None);
        assert_eq!(chunk(b"").text(), None);
        assert_eq!(chunk(b"   \0").text(), None);
        assert_eq!(chunk(b"bell\x07\0").text(), None);
    }

    #[test]
    fn soundfont_should_serialize_dump_structure_when_font_is_synthetic() {
        // given
        let font = crate::builder::test_font();

        // when
        let value = serde_json::to_value(&font).unwrap();

        // then
        assert_eq!(value["name"], "Fixture Font");
        assert_eq!(value["version"], serde_json::json!([2, 4]));
        assert_eq!(value["info"][0]["id"], "ifil");
        assert_eq!(value["info"][0]["text"], serde_json::Value::Null);
        assert_eq!(value["info"][0]["bytes"], 4);
        assert_eq!(value["info"][2]["text"], "Fixture Font");
        assert_eq!(value["sample_data_bytes"], font.sample_data.len());
        assert_eq!(value["sm24_bytes"], serde_json::Value::Null);
        assert_eq!(value["presets"][1]["program"], 48);
        assert_eq!(
            value["presets"][0]["zones"][0]["gens"][0]["name"],
            "instrument"
        );
        assert_eq!(
            value["instruments"][0]["zones"][0]["gens"][0]["name"],
            "sampleID"
        );
        assert_eq!(value["samples"][0]["name"], "piano-c4");
        assert_eq!(value["samples"].as_array().unwrap().len(), 4);
    }

    #[test]
    fn generator_name_should_resolve_spec_operators_when_defined() {
        // given / when / then
        assert_eq!(generator_name(GEN_INSTRUMENT), Some("instrument"));
        assert_eq!(generator_name(GEN_SAMPLE_ID), Some("sampleID"));
        assert_eq!(generator_name(17), Some("pan"));
        assert_eq!(generator_name(43), Some("keyRange"));
        assert_eq!(generator_name(14), None);
        assert_eq!(generator_name(999), None);
    }

    #[test]
    fn generator_value_should_decode_per_spec_type_when_operator_varies() {
        // given
        let pan = Generator {
            oper: 17,
            amount: u16::from_le_bytes((-500i16).to_le_bytes()),
        };
        let key_range = Generator {
            oper: GEN_KEY_RANGE,
            amount: u16::from_le_bytes([24, 96]),
        };
        let instrument = Generator {
            oper: GEN_INSTRUMENT,
            amount: 40_000,
        };

        // when / then
        assert_eq!(pan.value(), GeneratorValue::Signed(-500));
        assert_eq!(key_range.value(), GeneratorValue::Range { lo: 24, hi: 96 });
        assert_eq!(instrument.value(), GeneratorValue::Unsigned(40_000));
    }

    #[test]
    fn generator_should_serialize_decoded_value_when_dumped() {
        // given
        let vel_range = Generator {
            oper: GEN_VEL_RANGE,
            amount: u16::from_le_bytes([1, 127]),
        };
        let tune = Generator {
            oper: 51,
            amount: u16::from_le_bytes((-12i16).to_le_bytes()),
        };

        // when
        let vel_json = serde_json::to_value(vel_range).unwrap();
        let tune_json = serde_json::to_value(tune).unwrap();

        // then: raw amount kept, decoded value alongside
        assert_eq!(vel_json["amount"], 32_513);
        assert_eq!(vel_json["value"], serde_json::json!({"lo": 1, "hi": 127}));
        assert_eq!(tune_json["value"], -12);
    }

    #[test]
    fn generator_should_serialize_with_name_when_oper_is_known() {
        // given
        let known = Generator {
            oper: GEN_INSTRUMENT,
            amount: 7,
        };
        let unknown = Generator {
            oper: 999,
            amount: 1,
        };

        // when
        let known_json = serde_json::to_value(known).unwrap();
        let unknown_json = serde_json::to_value(unknown).unwrap();

        // then
        assert_eq!(known_json["name"], "instrument");
        assert_eq!(known_json["amount"], 7);
        assert_eq!(unknown_json["name"], serde_json::Value::Null);
    }

    #[test]
    fn fixed_name_should_render_text_when_formatted() {
        // given
        let name = FixedName::from_text("Piano");

        // when / then
        assert_eq!(format!("{name}"), "Piano");
        assert_eq!(format!("{name:?}"), "FixedName(\"Piano\")");
    }

    #[test]
    fn soundfont_should_return_no_version_when_ifil_is_truncated() {
        // given
        let font = SoundFont {
            info: vec![InfoChunk {
                id: *b"ifil",
                data: vec![2, 0],
            }],
            ..SoundFont::default()
        };

        // when / then
        assert_eq!(font.version(), None);
    }

    #[test]
    fn soundfont_should_report_sm24_usable_when_spec_conditions_hold() {
        // given: version 2.04, 4 sample points (8 bytes), exact sm24 size
        let mut font = SoundFont {
            info: vec![InfoChunk {
                id: *b"ifil",
                data: vec![2, 0, 4, 0],
            }],
            sample_data: vec![0; 8],
            sample_data_24: Some(vec![0; 4]),
            ..SoundFont::default()
        };

        // when / then
        assert!(font.sm24_usable());

        // version below 2.04 disqualifies it
        font.info[0].data = vec![2, 0, 1, 0];
        assert!(!font.sm24_usable());
        font.info[0].data = vec![2, 0, 4, 0];

        // size mismatch disqualifies it
        font.sample_data_24 = Some(vec![0; 3]);
        assert!(!font.sm24_usable());

        // an odd point count rounds the expected size up to even
        font.sample_data = vec![0; 6];
        font.sample_data_24 = Some(vec![0; 4]);
        assert!(font.sm24_usable());
        font.sample_data_24 = Some(vec![0; 3]);
        assert!(!font.sm24_usable());

        // empty smpl disqualifies it
        font.sample_data = Vec::new();
        font.sample_data_24 = Some(vec![0; 0]);
        assert!(!font.sm24_usable());
    }

    #[test]
    fn soundfont_should_expose_version_and_name_when_info_chunks_present() {
        // given
        let font = SoundFont {
            info: vec![
                InfoChunk {
                    id: *b"ifil",
                    data: vec![2, 0, 1, 0],
                },
                InfoChunk {
                    id: *b"INAM",
                    data: b"Test Font\0".to_vec(),
                },
            ],
            ..SoundFont::default()
        };

        // when / then
        assert_eq!(font.version(), Some((2, 1)));
        assert_eq!(font.name().as_deref(), Some("Test Font"));
    }

    fn sample_header_with_type(sample_type: u16) -> SampleHeader {
        SampleHeader {
            name: FixedName::from_text("s"),
            start: 0,
            end: 100,
            start_loop: 0,
            end_loop: 100,
            sample_rate: 44100,
            original_pitch: 60,
            pitch_correction: 0,
            sample_link: 0,
            sample_type,
        }
    }
}
