//! In-memory model of a `SoundFont` 2 file.
//!
//! The model is structured (presets own zones, zones own generators and
//! modulators) rather than flat like the on-disk `pdta` record arrays; the
//! flat bag/generator/modulator indices are resolved by [`crate::parse`] and
//! regenerated by [`crate::write`]. Instruments and samples are referenced by
//! index into [`SoundFont::instruments`] / [`SoundFont::samples`] from
//! generator amounts, exactly as on disk.

use std::fmt;

/// Length of the fixed name field in preset, instrument, and sample records.
pub const NAME_LEN: usize = 20;

/// Generator operator that links a preset zone to an instrument (spec: `instrument`, 41).
pub const GEN_INSTRUMENT: u16 = 41;
/// Generator operator that links an instrument zone to a sample (spec: `sampleID`, 53).
pub const GEN_SAMPLE_ID: u16 = 53;

/// `sfSampleType` flag marking a sample stored in ROM.
pub const SAMPLE_TYPE_ROM: u16 = 0x8000;
/// `sfSampleType` bits that indicate the sample participates in a linked
/// (stereo or chained) pair: `rightSample` (2), `leftSample` (4), `linkedSample` (8).
pub const SAMPLE_TYPE_LINKED_MASK: u16 = 2 | 4 | 8;
/// `sfSampleType` flag marking an Ogg-Vorbis-compressed sample.
///
/// This is the SF3 convention established by `MuseScore`: `dwStart`/`dwEnd`
/// are then byte offsets of the compressed stream, and loop points are
/// relative to the decoded sample.
pub const SAMPLE_TYPE_COMPRESSED: u16 = 0x10;

/// On-disk record sizes in bytes, used by the parser and writer.
pub(crate) mod record {
    pub const PHDR: usize = 38;
    pub const BAG: usize = 4;
    pub const MOD: usize = 10;
    pub const GEN: usize = 4;
    pub const INST: usize = 22;
    pub const SHDR: usize = 46;
}

/// A fixed-size, NUL-padded name exactly as stored in SF2 records.
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub struct FixedName(pub [u8; NAME_LEN]);

impl FixedName {
    /// Builds a name from text, truncated to 19 bytes and NUL-padded.
    #[must_use]
    pub fn from_text(text: &str) -> Self {
        let mut bytes = [0u8; NAME_LEN];
        for (slot, byte) in bytes.iter_mut().take(NAME_LEN - 1).zip(text.bytes()) {
            *slot = byte;
        }
        Self(bytes)
    }

    /// Renders the name for display: bytes up to the first NUL, lossily decoded.
    #[must_use]
    pub fn to_display(&self) -> String {
        let end = self.0.iter().position(|&b| b == 0).unwrap_or(NAME_LEN);
        String::from_utf8_lossy(&self.0[..end]).into_owned()
    }
}

impl fmt::Display for FixedName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.to_display())
    }
}

impl fmt::Debug for FixedName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "FixedName({:?})", self.to_display())
    }
}

/// A generator: an operator and its raw 16-bit amount.
///
/// The amount is kept as the raw little-endian `u16`; whether it means a
/// signed value, an unsigned value, or a byte range depends on the operator.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Generator {
    /// Generator operator (`SFGenerator` in the spec).
    pub oper: u16,
    /// Raw generator amount.
    pub amount: u16,
}

/// A modulator record (`sfModList`/`sfInstModList`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Modulator {
    /// Source modulator controller (`sfModSrcOper`).
    pub src_oper: u16,
    /// Destination generator (`sfModDestOper`).
    pub dest_oper: u16,
    /// Degree of modulation (`modAmount`).
    pub amount: i16,
    /// Secondary source controller (`sfModAmtSrcOper`).
    pub amount_src_oper: u16,
    /// Transform applied to the source (`sfModTransOper`).
    pub trans_oper: u16,
}

/// A preset or instrument zone: a modulator list and a generator list.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Zone {
    /// Generators, in on-disk order.
    pub gens: Vec<Generator>,
    /// Modulators, in on-disk order.
    pub mods: Vec<Modulator>,
}

impl Zone {
    /// The instrument this preset zone points to, if any.
    ///
    /// Per spec the `instrument` generator is the last one in the list; the
    /// last occurrence wins if a malformed file carries several.
    #[must_use]
    pub fn instrument_ref(&self) -> Option<u16> {
        last_amount(&self.gens, GEN_INSTRUMENT)
    }

    /// The sample this instrument zone points to, if any.
    #[must_use]
    pub fn sample_ref(&self) -> Option<u16> {
        last_amount(&self.gens, GEN_SAMPLE_ID)
    }
}

fn last_amount(gens: &[Generator], oper: u16) -> Option<u16> {
    gens.iter().rev().find(|g| g.oper == oper).map(|g| g.amount)
}

/// A preset (`phdr` record plus its resolved zones).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Preset {
    /// Preset name.
    pub name: FixedName,
    /// MIDI program number (`wPreset`).
    pub program: u16,
    /// MIDI bank number (`wBank`); 128 is the GM percussion bank.
    pub bank: u16,
    /// Reserved field preserved verbatim (`dwLibrary`).
    pub library: u32,
    /// Reserved field preserved verbatim (`dwGenre`).
    pub genre: u32,
    /// Reserved field preserved verbatim (`dwMorphology`).
    pub morphology: u32,
    /// Zones, in on-disk order; a leading global zone has no instrument generator.
    pub zones: Vec<Zone>,
}

/// An instrument (`inst` record plus its resolved zones).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Instrument {
    /// Instrument name.
    pub name: FixedName,
    /// Zones, in on-disk order; a leading global zone has no sample generator.
    pub zones: Vec<Zone>,
}

/// A sample header (`shdr` record). Offsets are in sample points (16-bit
/// words) into the `smpl` chunk, not bytes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SampleHeader {
    /// Sample name.
    pub name: FixedName,
    /// First sample point (`dwStart`).
    pub start: u32,
    /// One past the last sample point (`dwEnd`).
    pub end: u32,
    /// Loop start point (`dwStartloop`).
    pub start_loop: u32,
    /// Loop end point (`dwEndloop`).
    pub end_loop: u32,
    /// Sample rate in Hz (`dwSampleRate`).
    pub sample_rate: u32,
    /// Original MIDI key number (`byOriginalPitch`).
    pub original_pitch: u8,
    /// Pitch correction in cents (`chPitchCorrection`).
    pub pitch_correction: i8,
    /// Index of the linked sample when this one is part of a pair (`wSampleLink`).
    pub sample_link: u16,
    /// Sample type flags (`sfSampleType`).
    pub sample_type: u16,
}

impl SampleHeader {
    /// Whether the sample lives in ROM (no data in the `smpl` chunk).
    #[must_use]
    pub const fn is_rom(&self) -> bool {
        self.sample_type & SAMPLE_TYPE_ROM != 0
    }

    /// Whether the sample is one half of a linked (stereo/chained) pair.
    #[must_use]
    pub const fn is_linked(&self) -> bool {
        self.sample_type & SAMPLE_TYPE_LINKED_MASK != 0
    }

    /// Whether the sample data is an SF3 Ogg-Vorbis stream.
    #[must_use]
    pub const fn is_compressed(&self) -> bool {
        self.sample_type & SAMPLE_TYPE_COMPRESSED != 0
    }

    /// Length of the sample in sample points.
    #[must_use]
    pub const fn len_points(&self) -> u32 {
        self.end.saturating_sub(self.start)
    }

    /// Bytes this sample occupies in the `smpl` chunk: SF3-compressed
    /// streams store `end - start` bytes, PCM stores two bytes per point.
    #[must_use]
    pub fn stored_bytes(&self) -> u64 {
        let len = u64::from(self.len_points());
        if self.is_compressed() { len } else { len * 2 }
    }
}

/// A raw `INFO` sub-chunk, preserved verbatim and in order.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InfoChunk {
    /// Four-character chunk id (e.g. `ifil`, `INAM`).
    pub id: [u8; 4],
    /// Raw chunk payload.
    pub data: Vec<u8>,
}

/// A complete in-memory `SoundFont`.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct SoundFont {
    /// `INFO` sub-chunks, order preserved.
    pub info: Vec<InfoChunk>,
    /// Raw 16-bit little-endian sample data (`smpl` chunk).
    pub sample_data: Vec<u8>,
    /// Optional least-significant bytes for 24-bit samples (`sm24` chunk).
    pub sample_data_24: Option<Vec<u8>>,
    /// Presets, in on-disk order (terminal record excluded).
    pub presets: Vec<Preset>,
    /// Instruments, in on-disk order (terminal record excluded).
    pub instruments: Vec<Instrument>,
    /// Sample headers, in on-disk order (terminal record excluded).
    pub samples: Vec<SampleHeader>,
}

impl SoundFont {
    /// Number of 16-bit sample points in the `smpl` chunk.
    #[must_use]
    pub const fn sample_points(&self) -> usize {
        self.sample_data.len() / 2
    }

    /// Payload of the first `INFO` sub-chunk with the given id, if present.
    #[must_use]
    pub fn info_chunk(&self, id: [u8; 4]) -> Option<&[u8]> {
        self.info
            .iter()
            .find(|c| c.id == id)
            .map(|c| c.data.as_slice())
    }

    /// `SoundFont` format version from the `ifil` chunk, as (major, minor).
    #[must_use]
    pub fn version(&self) -> Option<(u16, u16)> {
        let data = self.info_chunk(*b"ifil")?;
        if data.len() < 4 {
            return None;
        }
        Some((
            u16::from_le_bytes([data[0], data[1]]),
            u16::from_le_bytes([data[2], data[3]]),
        ))
    }

    /// The index of `index`'s partner when the two samples link to each
    /// other mutually — the only linkage this crate trusts. One-directional
    /// links (common in real-world fonts, e.g. Fluid R3 types samples as
    /// left/right but leaves every `wSampleLink` at 0) are treated as broken.
    #[must_use]
    pub fn mutual_link(&self, index: usize) -> Option<usize> {
        let sample = self.samples.get(index)?;
        if !sample.is_linked() {
            return None;
        }
        let partner_index = usize::from(sample.sample_link);
        if partner_index == index {
            return None;
        }
        let partner = self.samples.get(partner_index)?;
        (partner.is_linked() && usize::from(partner.sample_link) == index).then_some(partner_index)
    }

    /// Whether the 24-bit extension can be used, per SF2.04 §6.3: requires a
    /// non-empty `smpl` chunk, format version 2.04 or later, and an `sm24`
    /// length of exactly one byte per sample point, rounded up to even.
    /// Unusable `sm24` data is preserved by the writer but ignored by
    /// extraction (and flagged by validation).
    #[must_use]
    pub fn sm24_usable(&self) -> bool {
        let Some(data_24) = &self.sample_data_24 else {
            return false;
        };
        if self.sample_data.is_empty() || self.version() < Some((2, 4)) {
            return false;
        }
        let points = self.sample_points();
        data_24.len() == points + (points & 1)
    }

    /// Bank name from the `INAM` chunk, if present.
    #[must_use]
    pub fn name(&self) -> Option<String> {
        let data = self.info_chunk(*b"INAM")?;
        let end = data.iter().position(|&b| b == 0).unwrap_or(data.len());
        Some(String::from_utf8_lossy(&data[..end]).into_owned())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fixed_name_should_truncate_text_when_longer_than_nineteen_bytes() {
        // given
        let text = "a very long instrument name indeed";

        // when
        let name = FixedName::from_text(text);

        // then
        assert_eq!(name.to_display(), "a very long instrum");
        assert_eq!(name.0[NAME_LEN - 1], 0);
    }

    #[test]
    fn fixed_name_should_round_trip_when_text_is_short() {
        // given
        let text = "Piano";

        // when
        let name = FixedName::from_text(text);

        // then
        assert_eq!(name.to_display(), "Piano");
    }

    #[test]
    fn fixed_name_should_stop_at_first_nul_when_garbage_follows() {
        // given
        let mut bytes = [b'x'; NAME_LEN];
        bytes[0] = b'A';
        bytes[1] = 0;

        // when
        let name = FixedName(bytes);

        // then
        assert_eq!(name.to_display(), "A");
    }

    #[test]
    fn zone_should_report_instrument_ref_when_instrument_generator_present() {
        // given
        let zone = Zone {
            gens: vec![
                Generator {
                    oper: 8,
                    amount: 1000,
                },
                Generator {
                    oper: GEN_INSTRUMENT,
                    amount: 7,
                },
            ],
            mods: vec![],
        };

        // when
        let inst = zone.instrument_ref();

        // then
        assert_eq!(inst, Some(7));
    }

    #[test]
    fn zone_should_report_no_instrument_ref_when_zone_is_global() {
        // given
        let zone = Zone {
            gens: vec![Generator {
                oper: 8,
                amount: 1000,
            }],
            mods: vec![],
        };

        // when
        let inst = zone.instrument_ref();

        // then
        assert_eq!(inst, None);
    }

    #[test]
    fn sample_header_should_report_rom_when_rom_flag_set() {
        // given
        let header = sample_header_with_type(SAMPLE_TYPE_ROM | 1);

        // when / then
        assert!(header.is_rom());
        assert!(!sample_header_with_type(1).is_rom());
    }

    #[test]
    fn sample_header_should_report_compressed_when_sf3_flag_set() {
        // given / when / then
        assert!(sample_header_with_type(SAMPLE_TYPE_COMPRESSED | 1).is_compressed());
        assert!(!sample_header_with_type(1).is_compressed());
    }

    #[test]
    fn sample_header_should_report_stored_bytes_when_compressed_or_plain() {
        // given
        let mut header = sample_header_with_type(1); // 100 points -> 200 bytes

        // when / then
        assert_eq!(header.stored_bytes(), 200);
        header.sample_type = SAMPLE_TYPE_COMPRESSED | 1; // 100 BYTES of Ogg
        assert_eq!(header.stored_bytes(), 100);
    }

    #[test]
    fn sample_header_should_report_linked_when_left_or_right_flag_set() {
        // given / when / then
        assert!(sample_header_with_type(2).is_linked());
        assert!(sample_header_with_type(4).is_linked());
        assert!(sample_header_with_type(8).is_linked());
        assert!(!sample_header_with_type(1).is_linked());
    }

    #[test]
    fn fixed_name_should_render_text_when_formatted() {
        // given
        let name = FixedName::from_text("Piano");

        // when / then
        assert_eq!(format!("{name}"), "Piano");
        assert_eq!(format!("{name:?}"), "FixedName(\"Piano\")");
    }

    #[test]
    fn soundfont_should_return_no_version_when_ifil_is_truncated() {
        // given
        let font = SoundFont {
            info: vec![InfoChunk {
                id: *b"ifil",
                data: vec![2, 0],
            }],
            ..SoundFont::default()
        };

        // when / then
        assert_eq!(font.version(), None);
    }

    #[test]
    fn soundfont_should_report_sm24_usable_when_spec_conditions_hold() {
        // given: version 2.04, 4 sample points (8 bytes), exact sm24 size
        let mut font = SoundFont {
            info: vec![InfoChunk {
                id: *b"ifil",
                data: vec![2, 0, 4, 0],
            }],
            sample_data: vec![0; 8],
            sample_data_24: Some(vec![0; 4]),
            ..SoundFont::default()
        };

        // when / then
        assert!(font.sm24_usable());

        // version below 2.04 disqualifies it
        font.info[0].data = vec![2, 0, 1, 0];
        assert!(!font.sm24_usable());
        font.info[0].data = vec![2, 0, 4, 0];

        // size mismatch disqualifies it
        font.sample_data_24 = Some(vec![0; 3]);
        assert!(!font.sm24_usable());

        // an odd point count rounds the expected size up to even
        font.sample_data = vec![0; 6];
        font.sample_data_24 = Some(vec![0; 4]);
        assert!(font.sm24_usable());
        font.sample_data_24 = Some(vec![0; 3]);
        assert!(!font.sm24_usable());

        // empty smpl disqualifies it
        font.sample_data = Vec::new();
        font.sample_data_24 = Some(vec![0; 0]);
        assert!(!font.sm24_usable());
    }

    #[test]
    fn soundfont_should_expose_version_and_name_when_info_chunks_present() {
        // given
        let font = SoundFont {
            info: vec![
                InfoChunk {
                    id: *b"ifil",
                    data: vec![2, 0, 1, 0],
                },
                InfoChunk {
                    id: *b"INAM",
                    data: b"Test Font\0".to_vec(),
                },
            ],
            ..SoundFont::default()
        };

        // when / then
        assert_eq!(font.version(), Some((2, 1)));
        assert_eq!(font.name().as_deref(), Some("Test Font"));
    }

    fn sample_header_with_type(sample_type: u16) -> SampleHeader {
        SampleHeader {
            name: FixedName::from_text("s"),
            start: 0,
            end: 100,
            start_loop: 0,
            end_loop: 100,
            sample_rate: 44100,
            original_pitch: 60,
            pitch_correction: 0,
            sample_link: 0,
            sample_type,
        }
    }
}
